<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xfkRzJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xfkRzJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xfkRzJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xfkRzJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xfkRzJ\App_KernelDevDebugContainer([
    'container.build_hash' => '5xfkRzJ',
    'container.build_id' => '9b1d4183',
    'container.build_time' => 1603224227,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xfkRzJ');
